# Generated by Django 5.1.1 on 2024-09-22 19:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0002_alter_company_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employee",
            options={"ordering": ["lastname", "firstname"]},
        ),
    ]
