# Generated by Django 5.1.1 on 2024-09-22 19:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0003_alter_employee_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employee",
            options={},
        ),
    ]
