# Generated by Django 5.1.1 on 2024-09-23 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0004_alter_employee_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="city",
            field=models.CharField(
                help_text="Company City", max_length=100, verbose_name="City"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(
                help_text="Company Name", max_length=100, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="phone",
            field=models.CharField(
                help_text="Company Phone", max_length=20, verbose_name="Phone"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="awards",
            field=models.TextField(
                blank=True, max_length=1000, null=True, verbose_name="Awards"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="city",
            field=models.CharField(
                help_text="Employee City", max_length=50, verbose_name="City"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="cluster",
            field=models.IntegerField(blank=True, null=True, verbose_name="Cluster"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="clusterable_text",
            field=models.TextField(
                blank=True, null=True, verbose_name="Clusterable Text"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="education",
            field=models.TextField(
                blank=True, max_length=1000, null=True, verbose_name="Education"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="experience",
            field=models.TextField(
                blank=True, max_length=1000, null=True, verbose_name="Experience"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="gender",
            field=models.CharField(
                choices=[("MALE", "MALE"), ("FEMALE", "FEMALE")],
                max_length=8,
                verbose_name="Gender",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="hobbies",
            field=models.TextField(
                blank=True, max_length=1000, null=True, verbose_name="Hobbies"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="other",
            field=models.TextField(
                blank=True, max_length=1000, null=True, verbose_name="Other"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="phone",
            field=models.CharField(
                help_text="Employee Phone", max_length=20, verbose_name="Phone"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="references",
            field=models.TextField(
                blank=True, max_length=1000, null=True, verbose_name="References"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="skills",
            field=models.TextField(max_length=1000, verbose_name="Skills"),
        ),
    ]
