# Generated by Django 5.1.1 on 2024-09-24 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0005_alter_company_city_alter_company_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Job_Post",
            fields=[
                ("job_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "job_title",
                    models.CharField(max_length=350, verbose_name="Job Title"),
                ),
                (
                    "jobDescription",
                    models.TextField(max_length=5000, verbose_name="Job Description"),
                ),
                (
                    "workhours",
                    models.TextField(max_length=1000, verbose_name="Work Hours"),
                ),
                ("contact", models.CharField(max_length=50, verbose_name="Contact")),
                ("city", models.CharField(max_length=50, verbose_name="City")),
                ("salary", models.CharField(max_length=50, verbose_name="Salary")),
                ("cluster", models.IntegerField(blank=True, null=True)),
                (
                    "added_date",
                    models.DateField(auto_now_add=True, verbose_name="Added on"),
                ),
                (
                    "clusterable_text",
                    models.TextField(
                        blank=True, null=True, verbose_name="Clusterable Text"
                    ),
                ),
                (
                    "company_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainapp.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Job Post",
                "ordering": ["-job_id"],
            },
        ),
    ]
