# Generated by Django 5.1.1 on 2024-09-24 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0006_job_post"),
    ]

    operations = [
        migrations.RenameField(
            model_name="job_post",
            old_name="company_id",
            new_name="company",
        ),
    ]
