# Generated by Django 5.1.1 on 2024-09-24 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0007_rename_company_id_job_post_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job_post",
            name="cluster",
            field=models.IntegerField(blank=True, null=True, verbose_name="Cluster"),
        ),
    ]
